spring: 
    prifiles:
    active:
    - dev
    
    
---   
spring: 
    prifiles: test
    application: 
        name: microservicecloud-test-config-atguigu-test    
---   
spring: 
    prifiles: dev
    application: 
        name: microservicecloud-dev-config-atguigu-dev
        
